name: Deploy to Goblin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GOAT: boat
  SSH_PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMoWztzYBEqj9NKuBL+ibe1ncBy2GImcEMMAssrOzSlQ jokes-rails@goblin.homework.quest"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh -o StrictHostKeyChecking=no jokes-rails@goblin.homework.quest bash deploy.sh
